--- #YAML:1.0
name:               Getopt-FileConfig
version:            1.00
abstract:           Module for taking options and their default values from a config-file.
author:
    - Matevz Tadel (matevz.tadel@cern.ch)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Long:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
